### ISSUE TITLE
Fortran Compiler with NAG library

### ISSUE THREAD

**Issue by nabobalis** [rcgsheffield/iceberg_software#121]
So I created a very basic fortran code that calls the NAG library just so I can figure how to compile it.
```fortran
PROGRAM ExampleNAG1


 USE nag_library, ONLY : A00AAF

        CALL A00AAF

END PROGRAM
```
I followed the [old doc](https://www.shef.ac.uk/cics/research/software/nag/icebergftn) and the [new doc](http://rcg.group.shef.ac.uk/iceberg/software/libs/nagfortran.html).

So after loading the intel compiler and using both,
```bash
ifort sourcefile.f90    $NAGLIB    -I$NAGINC
```
and
```bash
ifort your_code.f90 -lnag_mkl -o your_code.exe
```
it errored with 
```bash
catastrophic error: Too many errors, exiting
compilation aborted
```

However the examples worked when ran (nag_example a00aaf and nagexample24 d03phf)

The compile line for the first example is,
```bash
ifort -I/usr/local/packages5/nag/fll6i24dcl/nag_interface_blocks a00aaf.f90 -lnag_mkl -o a00aaf
```
and if I do the same with my example code, it compiles.

So is the nag_interface_blocks needed to compile the code every time?

**Comment by mikecroucher** [comment]
This works for me in a ``qrsh`` session using your code

module purge
module load compilers/intel/15.0.3 
module load libs/intel/15/ 
ifort nag_example.f90 -lnag_mkl -o your_code.exe

The order of loading modules seems to matter -- which is something we should look at. Could you confirm that this works OK please?

**Comment by nabobalis** [comment]
That works. I must of used the incorrect examples and tried to use the latest version of the NAG library. 

Sorry about that!
