### ISSUE TITLE
Install picard 1.129 

### ISSUE THREAD

**Issue by mikecroucher** [rcgsheffield/iceberg_software#135]
picard 1.129 https://github.com/broadinstitute/picard/releases/tag/1.129

(requires Java 1.6 there is info on this here http://broadinstitute.github.io/picard/building.html#BuildingPicardUtilities)

For Afsaneh S Maleki-Dizaji for teaching. Deadline October 26th

**Comment by Cadair** [comment]
Deadline 26/10 eh?!

**Comment by Cadair** [comment]
Do we need the version that supports reading from GA4GH API?

**Comment by mikecroucher** [comment]
I've emailed Afsaneh to ask

**Comment by mikecroucher** [comment]
He said 'no'

**Comment by mikecroucher** [comment]
The .zip file available from the releases section of the github repo contains binaries. Not sure what will be gained from compiling this from source. Going to use the binaries.
