### ISSUE TITLE
GEMINI Install

### ISSUE THREAD

**Issue by sann1458** [rcgsheffield/iceberg_software#161]
Please could we install this program for analysis and annotation of DNAseq data.  Here is all the info: http://gemini.readthedocs.org/en/latest/

Thanks

Johnathan

**Comment by mikecroucher** [comment]
It's installed but one of the tests failed. I have opened a ticket with the gemini developers to discuss this

https://github.com/arq5x/gemini/issues/621

**Comment by mikecroucher** [comment]
The failed test is nothing to worry about. See the discussion from the link above for details.
