### ISSUE TITLE
Freesurfer 

### ISSUE THREAD

**Issue by Cadair** [rcgsheffield/iceberg_software#164]
Supportworks request from: Marco Mcsweeney

**Comment by mikecroucher** [comment]
Download site here: http://freesurfer.net/

Freesurfer is known to produce differing results when used across platforms. http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0038234

We should inform our users of this. Having detailed documentation on the install procedure will be more important than usual here I think.

For extra caution, I'd suggest adding in flags in job submissions to ensure that all Freesurfer jobs run on the same architecture. Users should also record details of the architecture used for each run.

This is good practice anyway but is known to be relevant in this case.

**Comment by anthonybrookfield** [comment]
There may be licensing issues with this one too - https://surfer.nmr.mgh.harvard.edu/registration.html ?

**Comment by mikecroucher** [comment]
It appears to be a non-standard license agreement. Since IANAL,I have emailed the support mailing list explaining what we want to do and asking if we are permitted to install it so that all users of the cluster can access it.

If we need to ensure that each user has their own license, I propose that we shouldn't support it on our system.

**Comment by Cadair** [comment]
I hate licensing. Everything should be GPL or BSD :p

**Comment by mikecroucher** [comment]
The license will not be a problem. See the developer's response to my question at http://www.mail-archive.com/freesurfer@nmr.mgh.harvard.edu/msg43872.html

It seems that the only reason for the license mechanism is to allow them to record number of users and they do this to support future funding requests.

**Comment by Cadair** [comment]
@mikecroucher I can send them usage stats if they really wanted.

**Comment by mikecroucher** [comment]
That might be useful.

**Comment by mikecroucher** [comment]
The install is binary. I've done it but currently having trouble with an external library. The command

freeview -v $SUBJECTS_DIR/bert/mri/brainmask.mgz -v $SUBJECTS_DIR/bert/mri/aseg.mgz:colormap=lut:opacity=0.2 -f 

gives

freeview.bin: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

**Comment by mikecroucher** [comment]
yum whatprovides libXss.so.1

    libXScrnSaver-1.2.2-2.el6.i686 : X.Org X11 libXss runtime library

This is probably best installed using Yum.

**Comment by anthonybrookfield** [comment]
Yes, that version comes with the standard repos - should be installed now.

**Comment by mikecroucher** [comment]
Excellent. 
freeview -v $SUBJECTS_DIR/bert/mri/brainmask.mgz -v $SUBJECTS_DIR/bert/mri/aseg.mgz:colormap=lut:opacity=0.2 -f 

Now works!
