### ISSUE TITLE
git URL is wrong

### ISSUE THREAD

**Issue by drj11** [rcgsheffield/iceberg_software#166]
this page: http://rcg.group.shef.ac.uk/iceberg/software/compilers/git.html
references the install script https://github.com/rcgsheffield/iceberg_software/blob/master/software/install_scripts/compilers/git/install_git_5.2.sh but that install script doesn't exist there.

I found it in https://github.com/rcgsheffield/iceberg_software/blob/master/software/install_scripts/apps/git/install_git_2.5.sh (apps instead of compilers)

So we could fix the URL, sure, and I was about to submit a PR for that, but really the URL for the original page is wrong. Should be http://rcg.group.shef.ac.uk/iceberg/software/app/git.html and I'm not sure how to change that.

**Comment by Cadair** [comment]
@drj11 by your last statement do you mean that git is an "app" and not a "compiler" and therefore should be under apps?

If so, we have renamed "compilers" to "development tools" in the body of the documentation recently, the folder name and therefore URL has not been updated though.

If you could submit a patch for the first bug, I will look at renaming the compilers directory so the url makes more sense.

Thanks!!

**Comment by mikecroucher** [comment]
resolved by #173
