### ISSUE TITLE
ORCA Install

### ISSUE THREAD

**Issue by Cadair** [rcgsheffield/iceberg_software#167]
Requested by Stephen McCord

Website: https://orcaforum.cec.mpg.de/

**Comment by mikecroucher** [comment]
Its got a non-standard license

https://orcaforum.cec.mpg.de/license.html

Not sure if we can install it on a central system or not. The closest clause in the license to what we need is

5.This license is considered as a "Research group" license. Thus anyone who directly associated with your research group is covered by the license and may share your copy of ORCA on all computer resources of your group.

We are not a 'research group', however. We are a research support group and our 'computer resources' are for the entire University.

There is a forum post at https://orcaforum.cec.mpg.de/viewtopic.php?f=9&t=1904 (registration required) where someone asked for permission to install on a HPC system. The reply was 

'please let the HPC people contact Prof. F. Neese directly regarding how to
provide ORCA for their users in an easy way.'

So, I've emailed Prof Neese.
