### ISSUE TITLE
SCOTCH

### ISSUE THREAD

**Issue by Cadair** [rcgsheffield/iceberg_software#185]
Needed by OpenFOAM #182 

http://www.labri.fr/perso/pelegrin/scotch/

**Comment by mikecroucher** [comment]
This can be used by Code-Saturne too. It's an optional library that I didn't build for version 4.0 of Code-Saturne. We may as well use it for the next version of Code-Saturne we build though.

**Comment by Cadair** [comment]
well that makes it marginally less annoying.

**Comment by Cadair** [comment]
closed directly in master because I useless.
