### ISSUE TITLE
This repo is criminally missing any licence!

### ISSUE THREAD

**Issue by Cadair** [rcgsheffield/iceberg_software#186]

**Comment by mikecroucher** [comment]
I'm up for BSD

**Comment by Cadair** [comment]
some CC license is probably more appropriate seeing how it's not software for the most part?

**Comment by mikecroucher** [comment]
How about this: http://opendefinition.org/licenses/cc-by/

**Comment by Cadair** [comment]
:+1: on that

**Comment by mikecroucher** [comment]
We should check with Mike and Deniz before going ahead

**Comment by Cadair** [comment]
yes

**Comment by cs1ds** [comment]
Yes, I say go ahead.
