### ISSUE TITLE
Installation of WGCNA for R on iceberg

### ISSUE THREAD

**Issue by sann1458** [rcgsheffield/iceberg_software#193]
I am trying to install WGCNA for R as per: http://labs.genetics.ucla.edu/horvath/CoexpressionNetwork/Rpackages/WGCNA/InstallationInstructions.html

I tried to install it but I kept getting error messages.  Then tried a manual install but I don't think I have the correct privileges

**Comment by Cadair** [comment]
Hello, @sann1458.

I think you can install R packages into custom directories, ones which you will have permissions for. From reading this link: https://csgillespie.wordpress.com/2010/11/06/installing-r-packages/

I think you could do something like this:

```
mkdir /data/<username>/Rpackages
echo "R_LIBS=/data/<username>/Rpackages/` > ~/.Renviron
```
(swap `<username>` for your iceberg username)

and then install the packages following the instructions in the link you provided.

**Comment by mikecroucher** [comment]
@sann1458 Do you still need help with this or is it working now?

**Comment by mikecroucher** [comment]
No response. Assume all is OK and so closing. Please reopen if this issue is not resolved.
