### ISSUE TITLE
CUDA 7.5

### ISSUE THREAD

**Issue by mikecroucher** [rcgsheffield/iceberg_software#196]
Ricard Marxer requested CUDA 7.5

**Comment by mikecroucher** [comment]
I've done a preliminary install but it doesn't work. We need to update the device drivers.
Current docs are at http://rcg.group.shef.ac.uk/iceberg/software/libs/cuda.html

**Comment by rikrd** [comment]
What are the plans for updating the device drivers? I can imagine it may be a bit disruptive, but it could be tested on one device, see how it goes, and if no problems appear, do it for the rest.

**Comment by mikecroucher** [comment]
The device drivers have been updated. Documentation is now at http://docs.iceberg.shef.ac.uk/en/latest/software/libs/cuda.html
