### ISSUE TITLE
HTSeq installation

### ISSUE THREAD

**Issue by pouyan94** [rcgsheffield/iceberg_software#197]
http://www-huber.embl.de/HTSeq/doc/overview.html

**Comment by Cadair** [comment]
Hi!

Because this is a Python package it is easy for you to install using our new "conda" python install: http://rcg.group.shef.ac.uk/iceberg/software/apps/python.html

You will just need to run:

```bash
module load apps/python/conda

conda create -n htseq python=2 numpy matplotlib pip
source actiavte htseq
pip install htseq
```

**Comment by Cadair** [comment]
This will create a python environment in your home directory with numpy, matplotlib and HTSeq installed.
