### ISSUE TITLE
ffmpeg

### ISSUE THREAD

**Issue by drewleonard42** [rcgsheffield/iceberg_software#200]
Is there any chance ffmpeg could be installed? I'm trying to output some videos with matplotlib but I've had no luck doing it with the non-ffmpeg options available.

**Comment by rikrd** [comment]
+1 for this one.
It is very useful to decode and process audio in several formats.

**Comment by mikecroucher** [comment]
Done. Documentation at http://rcg.group.shef.ac.uk/iceberg/software/apps/ffmpeg.html
