### ISSUE TITLE
Phyluce

### ISSUE THREAD

**Issue by mikecroucher** [rcgsheffield/iceberg_software#202]
A request to install http://phyluce.readthedocs.org/en/latest/ by Susana Freitas

**Comment by Cadair** [comment]
They recommend you install this using conda. Therefore it is a very simple process for the user to install this:

```
module load apps/python/conda
module load apps/java/1.7.0u55

conda config --add channels https://conda.binstar.org/faircloth-lab
conda create -n phyluce phyluce
source activate phyluce
```

**Comment by Cadair** [comment]
If they always want this in their default environment I recommend they add this to their `.bashrc`:

```bash
if [ -f /usr/local/modulefiles/apps/python/conda ]; then                        
    module load apps/python/conda
    source activate phyluce
fi
```

**Comment by Cadair** [comment]
Also the people who write phyluce seem to maintain a lot of other packages as conda binaries, some of which we have installed for people recently: https://conda.anaconda.org/faircloth-lab

**Comment by mikecroucher** [comment]
Hmmmm smells of us telling the users 'do it yourself' which I'm not a major fan of.

How best for us to do this for the users and add it as an Environment module?

**Comment by mikecroucher** [comment]
install complete
