### ISSUE TITLE
.pdf build is broken

### ISSUE THREAD

**Issue by mikecroucher** [rcgsheffield/iceberg_software#214]
The .pdf build of the site isn't updating.

**Comment by Cadair** [comment]
I see what you did there...

**Comment by Cadair** [comment]
ok, so fun fact!

The PDF build is perfectly fine, just at some point we decided that the name of the documentation should be `Iceberg Documentation` rather than `iceberg Documentation`. So the correct pdf file is now `IcebergDocumentation.pdf`. I will update the link in the header.

**Comment by Cadair** [comment]
See 5f929f970

**Comment by mikecroucher** [comment]
oops. That was my fault. Thanks for fixing
