### ISSUE TITLE
cpanel is unreliable

### ISSUE THREAD

**Issue by mikecroucher** [rcgsheffield/iceberg_software#216]
We deploy this site to a University of Sheffield cPanel site. Several users have complained to me that the site is unreliable and this is ultimately because cPanel is unreliable.

Should we set things up so that we deploy to gh-pages as well as cPanel? That way, users can always have a backup.

**Comment by Cadair** [comment]
It would also be good to have a better URL. I will look into other hosting locations both internal and external.

**Comment by mikecroucher** [comment]
This is fixed now that we are on ReadTheDocs right?

**Comment by Cadair** [comment]
yep
