### ISSUE TITLE
pandoc install required

### ISSUE THREAD

**Issue by mikecroucher** [rcgsheffield/iceberg_software#229]
A test failed on bcbio because it required pandoc. We don't have pandoc. We need pandoc.

http://pandoc.org/installing.html

**Comment by Cadair** [comment]
That is going to be interesting...

**Comment by mikecroucher** [comment]
Whenever you say 'interesting' I get worried.

I see we need to install Haskell as a pre-req. How worried do I need to be do you think?

**Comment by Cadair** [comment]
I have never compiled Haskell. I have had issues installing pandoc on my desktop Linux machine.

So I would say fairly worried.

What does bcbio need pandoc for on iceberg? Can it not be done on the users machine?

**Comment by mikecroucher** [comment]
It uses pandoc as part of the test suite. 

I figured that it wouldn't matter too much if we installed pandoc from the RPM repos. Sadly, the version available is  pandoc-1.9.4.1-1.1.el6 and I need at least 1.12.

**Comment by mikecroucher** [comment]
I'm going to leave this until SHARC comes along. That will probably have a new-enough version from repos.
