### ISSUE TITLE
Travis latex error

### ISSUE THREAD

**Issue by mikecroucher** [rcgsheffield/iceberg_software#235]
Travis failed on the Latex build for my most recent commit. The HTML build was fine.

https://travis-ci.org/rcgsheffield/iceberg_software/builds/103313603

```
LaTeX Error: File `newfloat.sty' not found.
```

**Comment by Cadair** [comment]
what have you done :p

**Comment by mikecroucher** [comment]
newfloat.sty is in the apt package texlive-latex-recommended according to http://packages.ubuntu.com/trusty/all/texlive-latex-recommended/filelist

I've added that package to the travis yaml file. Still get the error message.
So, what am I missing here?

**Comment by Cadair** [comment]
I am going to commit stuff straight onto master to debug.

**Comment by Cadair** [comment]
ok, I have no idea what the hell is going on here.

**Comment by mikecroucher** [comment]
me either. I didn't touch it honest!

**Comment by mikecroucher** [comment]
The .pdf we publish is building fine. This error is confined to travis.

**Comment by mikecroucher** [comment]
The Travis build is working now. Needed to manually put the .sty file in the same directory as the latex file in the _build/latex directory. Clearly its not in the latex packages now! Feels ugly. If anyone can think of a better way, that would be great.

Sadly, the website isn't building now :(

**Comment by Cadair** [comment]
@mikecroucher on travis or the actual build bot?

**Comment by mikecroucher** [comment]
Actual build bot. How do I debug?

**Comment by Cadair** [comment]
yeah it is turbo broke.

**Comment by mikecroucher** [comment]
Can't we switch to having the generated html on github  pages and point the
URL there?

create a local build script that works a la Nikola that pushes generated
html to the right branch.

That way...no build server to break.

**Comment by Cadair** [comment]
Switching to Read the Docs would be the best option I think, I am working on it.

**Comment by mikecroucher** [comment]
Sorted.
