### ISSUE TITLE
Java8 virtual memory

### ISSUE THREAD

**Issue by anthonybrookfield** [rcgsheffield/iceberg_software#243]
Java is bad and requests lots of virtual memory on startup (usually a given fraction of the physical memory on a node, which can be quite a lot on Iceberg) which then exceeds a users virtual memory limit set by the scheduler.  Requesting more virtual memory for the job will let Java start, but uses up resources unnecessarily and can result in long queue times...   Previously Deniz had a wrapper around the java installs to set Java's Xmx parameter to a reasonable value....  e.g. for 1.7.0_55 'java' is actually a wrapper for:

```
  if test -z "`echo $* | grep -e -Xmx`"; then
# user has not specified -Xmx memory requirement flag, so add it. 
    /usr/local/packages6/java/jdk1.7.0_55/bin/java -Xmx1G $* 
else
# user specified the -Xmx flag, so don't add it. 
    /usr/local/packages6/java/jdk1.7.0_55/bin/java $*
fi  
```

Could do similar for Java 8?

**Comment by mikecroucher** [comment]
Agreed. Will do
