### ISSUE TITLE
bcbio additional genome -- mouse mm10 

### ISSUE THREAD

**Issue by ssamberkar** [rcgsheffield/iceberg_software#262]
Hi Mike,

Could you please include the mouse genome (http://hgdownload.cse.ucsc.edu/downloads.html#mouse)
in bcbio build 0.9.6a?

Many thanks.
Best,
Sandeep

**Comment by mikecroucher** [comment]
Thanks Sandeep. Do you or brad have any notes on how to go about doing this?

**Comment by ssamberkar** [comment]
I think the procedure might be the same as adding a custom genome with associated annotation and tag the aligners with which one wants to use the genome with. I'd confirm this with Rory though.

**Comment by mikecroucher** [comment]
This is done.
The documentation will be updated soon. The commit for the docs is at 

https://github.com/mikecroucher/iceberg_software/commit/fef0298ca5e12f6544d4a6b5aba2dd0f0f49a871

As is usually the case for us and bcbio, the supported install method stalled on the STAR part so I had to run it manually. 

Another issue is that rhese upgrades appear not to be updating the $BCBIO_DIR/config/install-params.yaml file! I'll raise it with brad et al
