### ISSUE TITLE
bcbio -- mouse RNAseq error

### ISSUE THREAD

**Issue by ssamberkar** [rcgsheffield/iceberg_software#274]
Hi @roryk, @mikecroucher 

Now I could start the run and bcbio finds the mouse genome location but now it throws an error of not finding a GTF file. Again, I checked in the /genomes folder and I could see corresponding GTF files in /rnaseq folder. Looks like we're again missing a tiny link..

Traceback log attached 

[tdp43_mouse_analysis.SGE.e1065201.txt](https://github.com/rcgsheffield/iceberg_software/files/153370/tdp43_mouse_analysis.SGE.e1065201.txt)

**Comment by roryk** [comment]
Sorry for the problems, it looks like installing outside of the normal way of doing it broke some things. The extra annotations comes from the file in the `seq` directory called `mm10-resources.yaml`. It should look like this one:

https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/config/genomes/mm10-resources.yaml

Is that file there? Does it have that?

**Comment by ssamberkar** [comment]
Right, we're missing most of the stuff in the yaml file, we are just having
the first 2 lines.
Rory, do you think it is worthwhile to redo the whole genome installation
step rather than fixing these issues manually?

On 1 March 2016 at 18:49, Rory Kirchner <notifications@github.com> wrote:

> Sorry for the problems, it looks like installing outside of the normal way
> of doing it broke some things. The extra annotations comes from the file in
> the seq directory called mm10-resources.yaml. It should look like this
> one:
>
>
> https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/config/genomes/mm10-resources.yaml
>
> Is that file there? Does it have that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rcgsheffield/iceberg_software/issues/274#issuecomment-190849512>
> .
>



-- 
--
Warm Regards
Sandeep Amberkar

**Comment by roryk** [comment]
I'm not sure why the mm10 file is missing all of those lines, it should be pulling it down with the genome install.

I thought the issue was that for some reason running STAR via the command line worked but it stalled when running the command line generated by the bcbio mm10 install. Does that issue still exist? If not then just using the bcbio install is the way to go.

**Comment by roryk** [comment]
I added the option to pass more cores to `bcbio_nextgen.py upgrade`, so the STAR indexer will be able to run multithreaded here: https://github.com/chapmanb/bcbio-nextgen/commit/fd214c7c9350319440633cd167924845dd87c8ea

**Comment by mikecroucher** [comment]
@roryk Yes, the STAR issue still exists. I think it's not a multicore issue. If it was, it would complete eventually...it would just be slower. As it is, the STAR step *never* completes when called from within bcbio_upgrade

**Comment by roryk** [comment]
Just running the STAR indexing from the command line works though? bcbio isn’t doing anything special, it is doing exactly that, so it is super confusing why it works running it manually but not within bcbio.

**Comment by mikecroucher** [comment]
@roryk - I agree, super-confusing! Possible that there's some bizarre interaction with our rather aged cluster. Hopefully, the replacement thats due to come online this year will be less painful!

Regarding getting this fixed. Although I'd like to do a fully-automated re-install as @ssamberkar suggests, I'm fairly sure we'll just hit the same problem. It will fail at the STAR step and I'll have to manually slog through the broken bits.

So, @roryk will it be OK to just copy the .yaml file you linked to?

**Comment by roryk** [comment]
Yep, just copying the YAML file should work.

**Comment by roryk** [comment]
It would be great to figure out why the STAR command is failing though. Could you try running the install in bcbio and running strace on the process that is stuck and see what it is doing?

**Comment by mikecroucher** [comment]
I've updated the YAML file. @ssamberkar - could you try it now pls?

@roryk -- Last time I did an strace, there was no output while the STAR job was stalling. I'll follow this up when I get chance

**Comment by ssamberkar** [comment]
Thanks, Mike.
I'll give it a spin and let you know if it goes through.

On 14 March 2016 at 08:56, Mike Croucher <notifications@github.com> wrote:

> I've updated the YAML file. @ssamberkar <https://github.com/ssamberkar> -
> could you try it now pls?
>
> @roryk <https://github.com/roryk> -- Last time I did an strace, there was
> no output while the STAR job was stalling. I'll follow this up when I get
> chance
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rcgsheffield/iceberg_software/issues/274#issuecomment-196210213>
> .
>



-- 
--
Warm Regards
Sandeep Amberkar

**Comment by mikecroucher** [comment]
Did it go through?

**Comment by ssamberkar** [comment]
Yes Mike, it did quite successfully.
Cheers,
Sandeep

On 20 March 2016 at 12:05, Mike Croucher <notifications@github.com> wrote:

> Did it go through?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/rcgsheffield/iceberg_software/issues/274#issuecomment-198913253>
>



-- 
--
Warm Regards
Sandeep Amberkar
