### ISSUE TITLE
Minor shell coding style in `qrshx`

### ISSUE THREAD

**Issue by drj11** [rcgsheffield/iceberg_software#278]
The page at https://github.com/rcgsheffield/iceberg_software/blob/master/software/scheduler/qrshx.rst says that the `qrshx` command is a script that does:

```
qrsh -v DISPLAY -pty y $* bash
```

The `$*` should be `"$@"` (note: with the double quotes). It's just better. When the arguments have spaces in them.

**Comment by drj11** [comment]
See http://stackoverflow.com/questions/2761723/what-is-the-difference-between-and-in-shell-scripts for further reading and advice.

**Comment by Cadair** [comment]
@anthonybrookfield ping

**Comment by mikecroucher** [comment]
Another user suggested the following to me in email

```
You could prepend an 'exec' to the command line to avoid the invoking shell taking a process slot:
#!/bin/sh
exec qrsh -v DISPLAY -pty y $* bash
```

Any thoughts on this?

**Comment by drj11** [comment]
the final `exec` is a premature optimisation. The 1980's called and they want it back.

**Comment by anthonybrookfield** [comment]
this is going to be the best damned 1 line shell script ever.  changes made.

**Comment by Cadair** [comment]
Can someone update the docs with the lastest script as well? Thanks.

**Comment by mikecroucher** [comment]
@drj11 please help me out...I was educated in the 90s.
What's wrong with the exec?

**Comment by mikecroucher** [comment]
User who suggested it has opened #280

**Comment by mikecroucher** [comment]
@anthonybrookfield There's so much interest because the default `qsh` is horrible! I got bought a cup of coffee last week for showing this to a regular user. Her comment 'You've changed my life!'

**Comment by drj11** [comment]
@mikecroucher On the final `exec` thing: All it does is replace the shell's process with the `qrsh` process. Hence, no new process is created. We save a whole process slot! We save having to keep a `bash` around until `qrsh` exits! Now in the 1970's this may have been an issue where there was only 2MB RAM and 64 process slots, but I don't think it's been an issue since about 1986.

There's potential for future bugs, for example, adding `echo goodbye` as the last line of `qrshx` won't work as the `exec` means that the `echo` will never get executed. But that's weak I think.

However, the real problem is that many Unix old-hands just reflexively put `exec` before the last line of a script and they cannot change their ways.
