### ISSUE TITLE
Update to the qrshx script

### ISSUE THREAD

**Issue by abiancardi** [rcgsheffield/iceberg_software#280]
Hi,
I really liked the `qrshx` script - it's a very handy trick!

Maybe an `exec` could be prepended to the command line to avoid that the invoking shell keeps using a process slot on the headnodes and use `"$@"` to quote each argument passed to the script (just in case):
```
    #!/bin/sh
    exec qrsh -v DISPLAY -pty y "$@" bash
```

Best,
Alberto

**Comment by mikecroucher** [comment]
Thanks for that. I took your suggestion and included it in #278
