### ISSUE TITLE
G++ compilation fail for R bigmemory

### ISSUE THREAD

**Issue by ssamberkar** [rcgsheffield/iceberg_software#288]
Hello,

I'm trying to install an R package, bigmemory, that seems to require explicit g++ for compilation. I tried it with all gcc compilers Iceberg has but it always produces the following error:

`* installing *source* package ‘bigmemory’ ...
** package ‘bigmemory’ successfully unpacked and MD5 sums checked
  checking for Sun Studio compiler...no
  checking for OS...Linux
** libs
g++-4.9.2 -I/usr/local/packages6/R/3.2.0/lib64/R/include -DNDEBUG -I../inst/include -DLINUX -I/usr/local/include -I"/home/md4zsa/R/x86_64-unknown-linux-gnu-library/3.2/BH/include" -I"/home/md4zsa/R/x86_64-unknown-linux-gnu-library/3.2/Rcpp/include"  -fopenmp -fpic  -g -O2  -c BigMatrix.cpp -o BigMatrix.o
/bin/sh: g++-4.9.2: command not found
make: *** [BigMatrix.o] Error 127
ERROR: compilation failed for package ‘bigmemory’
* removing ‘/home/md4zsa/R/x86_64-unknown-linux-gnu-library/3.2/bigmemory’
ERROR: dependency ‘bigmemory’ is not available for package ‘biganalytics’
* removing ‘/home/md4zsa/R/x86_64-unknown-linux-gnu-library/3.2/biganalytics’`

Any smart work around this which I may be missing?

**Comment by mikecroucher** [comment]
The telling line is this:-

`/bin/sh: g++-4.9.2: command not found`

Our `g++` binaries are simply called `g++`

Some linux distros allow multiple versions of g++ to be installed by appending the version number. This package seems to assume that you are definitely using one of those distros.

**Comment by ssamberkar** [comment]
Yeah, that was puzzling, I could see that it is installed yet the R compilation threw an error. I tried using the 4.9.2 as well but the same error persisted.

**Comment by mikecroucher** [comment]
I'm wondering if there is something strange with your environment. I just tried it using my test account which has the same permissions as any user and

    install.packages('bigmemory')

worked fine. It did not try to call `g++-4.9.2`. It called `g++` as I'd expect and installed.
As a first step, I suggest doing a 

    module purge

to remove all modules. Then load the R module

    module load apps/R/3.2.4

and try again. If this doesn't work, I'd ask myself if there's anything strange in your .bashrc file.

**Comment by mikecroucher** [comment]
Same problem as #326. Now resolved
