### ISSUE TITLE
KNIME 2.10.4 Installation

### ISSUE THREAD

**Issue by lucyantie** [rcgsheffield/iceberg_software#298]
Hi,

Appreciate if you could help to install KNIME versioni 3.1.2 :)

Many thanks

Lucy

**Comment by Cadair** [comment]
Hi, sorry this is taking so long.

What in particular do you need, there seems to be many options: https://www.knime.org/server-products

**Comment by lucyantie** [comment]
Hi Cadair,

Thank you for your email. 

From this [link](https://www.knime.org/downloads/overview), I particularly need the "KNIME Analytics Platform + all free extensions for Linux" for 64-bit Version 3.1.2

It is an open source application. From your given link, you can click on the 'Download now' button to access to the software list.

**Comment by mikecroucher** [comment]
This has now been done I believe. #310
