### ISSUE TITLE
g++ not found error

### ISSUE THREAD

**Issue by ssamberkar** [rcgsheffield/iceberg_software#326]
Despite having g++ in the path and gcc 5.3 loaded, I get the error that "g++ - 4.9.2 not found" during the installation of Rcpp. I repeated this by unloading gcc 5.3 and loading 4.9.2, only to get the same error (see below):
`
* installing to library ‘/home/md4zsa/R/x86_64-pc-linux-gnu-library/3.3’
* installing *source* package ‘Rcpp’ ...
** package ‘Rcpp’ successfully unpacked and MD5 sums checked
** libs
g++-4.9.2 -I/usr/local/packages6/R/3.3.0/lib64/R/include -DNDEBUG -I../inst/include/ -I/usr/local/include   -fopenmp -fpic  -g -O2  -c Date.cpp -o Date.o
make: g++-4.9.2: Command not found
make: *** [Date.o] Error 127
ERROR: compilation failed for package ‘Rcpp’
* removing ‘/home/md4zsa/R/x86_64-pc-linux-gnu-library/3.3/Rcpp’

`

I checked by ~/.bashrc, it only has couple of aliases and nothing that points any executable that might interfere with g++. Rcpp and Hmisc form the basis of many bioinformatics oriented packages - namely, WGCNA.

**Comment by mikecroucher** [comment]
Hi Sandeep

In a fresh session, I did this

First, start an interactive session on the worker node

`qrshx`

Load the R module

`module load apps/R/3.3.0`

launch R and install Rcpp

```
> install.packages('Rcpp')
Installing package into ‘/home/fe4test/R/x86_64-pc-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://www.stats.bris.ac.uk/R/src/contrib/Rcpp_0.12.5.tar.gz'
Content type 'application/x-gzip' length 2397088 bytes (2.3 MB)
==================================================
downloaded 2.3 MB

* installing *source* package ‘Rcpp’ ...
** package ‘Rcpp’ successfully unpacked and MD5 sums checked
** libs
g++ -I/usr/local/packages6/R/3.3.0/lib64/R/include -DNDEBUG -I../inst/include/ -I/usr/local/include    -fpic  -g -O2  -c Date.cpp -o Date.o
g++ -I/usr/local/packages6/R/3.3.0/lib64/R/include -DNDEBUG -I../inst/include/ -I/usr/local/include    -fpic  -g -O2  -c Module.cpp -o Module.o
g++ -I/usr/local/packages6/R/3.3.0/lib64/R/include -DNDEBUG -I../inst/include/ -I/usr/local/include    -fpic  -g -O2  -c Rcpp_init.cpp -o Rcpp_init.o
g++ -I/usr/local/packages6/R/3.3.0/lib64/R/include -DNDEBUG -I../inst/include/ -I/usr/local/include    -fpic  -g -O2  -c api.cpp -o api.o
g++ -I/usr/local/packages6/R/3.3.0/lib64/R/include -DNDEBUG -I../inst/include/ -I/usr/local/include    -fpic  -g -O2  -c attributes.cpp -o attributes.o
g++ -I/usr/local/packages6/R/3.3.0/lib64/R/include -DNDEBUG -I../inst/include/ -I/usr/local/include    -fpic  -g -O2  -c barrier.cpp -o barrier.o
g++ -shared -L/usr/local/packages6/R/3.3.0/lib64/R/lib -L/usr/local/lib/gcc/blas/1 -L/usr/local/lib/gcc/lapack/3_3_0 -L/usr/local/packages6/libs/gcc/4.4.7/bzip2/1.0.6/lib/ -o Rcpp.so Date.o Module.o Rcpp_init.o api.o attributes.o barrier.o -L/usr/local/packages6/R/3.3.0/lib64/R/lib -lR
installing to /home/fe4test/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (Rcpp)

The downloaded source packages are in
	‘/tmp/1847550.1.shortint.q/RtmpKUGjhI/downloaded_packages’
> 
```

Everything worked just fine.

This was from a test account that has no special privileges.

So, the site-wide installation of R is fine.

There must be something in your environment that is setting the c++ compiler to be `g++-4.9.2` -- an executable that does not exist on iceberg.
 
As mentioned in email, I'll come to take a look on Tuesday afternoon when I'm next in SITRAN.

Cheers,
Mike

**Comment by mikecroucher** [comment]
Met up with Sandeep and cleared up various things in his user profile including a hidden .R folder, a strange looking .bash_profile and various other bits and pieces that looked odd. 

Problem went away although still not 100% sure what was causing it other than 'polluted environment'
