### ISSUE TITLE
How best to include examples?

### ISSUE THREAD

**Issue by mikecroucher** [rcgsheffield/iceberg_software#37]
I've added a HelloWorld example in .cpp

https://github.com/mikecroucher/iceberg_software/blob/master/software/compilers/examples/helloworld/hello.cpp

to allow us to refer to something explicit when writing how to use the various compilers.

How should we be referring to such files in the text?  Options include

* Link to the github url (but may lead to people struggling to download it)
* Include the code explicitly in the text so users copy and paste
* A separate iceberg-examples repo - we could encourage users to git-clone this to get all examples.

As I write this, I'm favouring the final option. Thoughts?

**Comment by Cadair** [comment]
You could include the source code in the doc repo as a cpp file then literal include it and provide a download link? http://sphinx-doc.org/markup/code.html#includes
