### ISSUE TITLE
Front Page Discussion

### ISSUE THREAD

**Issue by mikecroucher** [rcgsheffield/iceberg_software#47]
The current front page of the website is very sparse. What else is required?

**Comment by Cadair** [comment]
To be fair, there is not much on the current homepage...

**Comment by Cadair** [comment]
I think the formatting of the home page could do with improving, it looks a little cluttered at the moment.

Also a couple of sentences describing the scope of the service and the documentation would we good as well.

**Comment by mikecroucher** [comment]
We should also bear in mind that this is the homepage for **iceberg** and, as such, should not include links to things such as news, events and success stories. I think that such things should go in the Research IT website within which the iceberg site will be embedded.

**Comment by Cadair** [comment]
We should include cluster update news, like new software or deprecations
etc. A bit like the current 'news' functionality on iceberg at the moment.

Stuart

**Comment by mikecroucher** [comment]
I shifted things around recently. Looks better I think.

**Comment by mikecroucher** [comment]
bumping this.

**Comment by Cadair** [comment]
What are peoples opinions on the current state of the home page, which has changed a fair bit since this issue was spawned.

**Comment by mikecroucher** [comment]
Looks good to me. I'm happy to close

**Comment by mikecroucher** [comment]
The front page is fine now I think.
