### ISSUE TITLE
What variant of the SGE do we use?

### ISSUE THREAD

**Issue by mikecroucher** [rcgsheffield/iceberg_software#49]
I can't find any details in the old docs.

**Comment by mikeg64** [comment]
Son of Grid Engine

On 26 June 2015 at 10:36, mikecroucher <notifications@github.com> wrote:

> I can't find any details in the old docs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rcgsheffield/iceberg_software/issues/49>.
>



-- 
Dr Michael Griffiths
Research Computing Manager
Corporate Information and Computing Services
The University of Sheffield

Tel: 0114 2221126

**Comment by mikecroucher** [comment]
Thanks. Added to the glossary.
