### ISSUE TITLE
Which version of gcc was used to build the hdf5 library?

### ISSUE THREAD

**Issue by mikecroucher** [rcgsheffield/iceberg_software#6]
I want to build something that links to it. I'm guessing that the gcc version matters...but could be wrong of course.

**Comment by Cadair** [comment]
which one? I compiled many... They are sorted by compiler under packages6

**Comment by mikecroucher** [comment]
But the only thing that's listed is gcc or intel, right? Not the version?
Or have I missed something

**Comment by Cadair** [comment]
```
testnode02 $ ls /usr/local/packages6/hdf5/
gcc-4.4.7  gcc-4.8.2  hdf5-1.8.9.delete  hdf5.rst  intel-14.0  openmpi-1.8.3
```

**Comment by Cadair** [comment]
or have I missed something?!

**Comment by mikecroucher** [comment]
You missed documenting this ;)
I didn't look in that location to be honest. I just went on what's in the documentation and what I could see when I did `module avail`

**Comment by mikecroucher** [comment]
Looking at the module files, we currently have:
`libs/hdf5/gcc/1.8.13` - points to the gcc 4.8.2 build
`libs/hdf5/gcc/1.8.13` - points to the gcc 4.8.2 build
`libs/hdf5/gcc/openmpi/1.8.13` - unclear which version of gcc built it
`libs/hdf5/gcc/openmpi/1.8.14` - points to a gcc 4.4.7 build

Another minor issue is that in the openmpi/1.8.14 modulefile, we have
`set hdf5version 1.8.13` 

I'm reluctant to wade in myself here because the hdf5 libs are  currently a mystery to me.

**Comment by mikecroucher** [comment]
I think I need hdf5 1.8.14 built with gcc 4.8.2 and with openmpi support. How much work is involved in building it?

**Comment by Cadair** [comment]
we only have mpi builds for gcc 4.4.7 at the moment, so if you want hdf5 with a newer gcc and openmpi you will have to talk to anthony about building openmpi.

All the openmpi + gcc builds are therefore 4.4.7

**Comment by mikecroucher** [comment]
Thanks.
