### ISSUE TITLE
HDF5: SZIP Encoder and ZLIB?

### ISSUE THREAD

**Issue by mikecroucher** [rcgsheffield/iceberg_software#8]
I'm building a library that depends on HDF5. Its config tool is asking me if HDF5 needs SZIP and ZLIB. I have no idea how to answer this!

I note that pre-built binaries at https://www.hdfgroup.org/HDF5/release/obtain5.html have been built with these enabled. How were ours built? How might I find out?

**Comment by mikecroucher** [comment]
`ldd /usr/local/packages6/hdf5/gcc-4.4.7/openmpi-1.8.3/hdf5-1.8.14/lib/libhdf5.so`

gives 

	linux-vdso.so.1 =>  (0x00007fff006ae000)
	libz.so.1 => /lib64/libz.so.1 (0x00002ba476a21000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00002ba476c38000)
	libm.so.6 => /lib64/libm.so.6 (0x00002ba476e3c000)
	libmpi.so.1 => /usr/local/mpi/gcc/openmpi/1.8.3/lib/libmpi.so.1 (0x00002ba4770c0000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002ba477399000)
	libc.so.6 => /lib64/libc.so.6 (0x00002ba4775b6000)
	/lib64/ld-linux-x86-64.so.2 (0x0000003208200000)
	libopen-rte.so.7 => /usr/local/mpi/gcc/openmpi/1.8.3/lib/libopen-rte.so.7 (0x00002ba47794a000)
	libopen-pal.so.6 => /usr/local/mpi/gcc/openmpi/1.8.3/lib/libopen-pal.so.6 (0x00002ba477bc4000)
	librt.so.1 => /lib64/librt.so.1 (0x00002ba477e96000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00002ba47809e000)

So I'm guessing with have zlib support (from libz.so) but not szip support. Can anyone confirm please?

**Comment by mikeg64** [comment]
Hi
This is owned by Stuart

You are right you should expect lib names like

libsz.a libsz.a libsz.so.2

MikeG



On 11 June 2015 at 09:40, mikecroucher <notifications@github.com> wrote:

> ldd
> /usr/local/packages6/hdf5/gcc-4.4.7/openmpi-1.8.3/hdf5-1.8.14/lib/libhdf5.so
>
> gives
>
> linux-vdso.so.1 =>  (0x00007fff006ae000)
> libz.so.1 => /lib64/libz.so.1 (0x00002ba476a21000)
> libdl.so.2 => /lib64/libdl.so.2 (0x00002ba476c38000)
> libm.so.6 => /lib64/libm.so.6 (0x00002ba476e3c000)
> libmpi.so.1 => /usr/local/mpi/gcc/openmpi/1.8.3/lib/libmpi.so.1 (0x00002ba4770c0000)
> libpthread.so.0 => /lib64/libpthread.so.0 (0x00002ba477399000)
> libc.so.6 => /lib64/libc.so.6 (0x00002ba4775b6000)
> /lib64/ld-linux-x86-64.so.2 (0x0000003208200000)
> libopen-rte.so.7 => /usr/local/mpi/gcc/openmpi/1.8.3/lib/libopen-rte.so.7 (0x00002ba47794a000)
> libopen-pal.so.6 => /usr/local/mpi/gcc/openmpi/1.8.3/lib/libopen-pal.so.6 (0x00002ba477bc4000)
> librt.so.1 => /lib64/librt.so.1 (0x00002ba477e96000)
> libutil.so.1 => /lib64/libutil.so.1 (0x00002ba47809e000)
>
> So I'm guessing with have zlib support (from libz.so) but not szip
> support. Can anyone confirm please?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rcgsheffield/iceberg_software/issues/8#issuecomment-111043204>
> .
>



-- 
Dr Michael Griffiths
Research Computing Manager
Corporate Information and Computing Services
The University of Sheffield

Tel: 0114 2221126

**Comment by mikecroucher** [comment]
Great. I'll update the documentation. Thanks.
