### ISSUE TITLE
How to handle multiple versions of the same lib

### ISSUE THREAD

**Issue by Cadair** [rcgsheffield/iceberg_software#93]
At the moment we have one page per version, is this the best way? 

What about subsections on one pages?

**Comment by mikecroucher** [comment]
I've merged the two Boost pages: #168 and added a third version!

**Comment by Cadair** [comment]
I think that way is better.

**Comment by Cadair** [comment]
@mikecroucher Shall we take the one approach for different compilers as well, at the moment we have a HDF5 page for gcc and pgi?
